services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${username}
      - POSTGRES_PASSWORD=${password}
      - POSTGRES_DB=${database}

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://${username}:${password}@db:5432/${database}
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
